(function(g){var window=this;'use strict';var j1=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},k1=function(a){return g.oB(a)&&!a.K("web_player_i_see_captions_3_killswitch")},dXa=function(a,b){var c,d,e;
return g.B(function(f){if(1==f.j)return c=a+"|"+b,g.A(f,g.ds(),2);if(3!=f.j){d=f.u;if(!d)throw g.zr("gct");return g.A(f,g.HC(d),3)}e=f.u;return f.return(e.get("captions",c))})},eXa=function(a,b){var c=new g.KC;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},fXa=function(a,b,c){dXa(a,b).then(function(d){d&&c(d.trackData,new g.KC(d.metadata))})},l1=function(){this.segments=[]},gXa=function(a,b){var c=g.hc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Wb(a.segments,c),g.Wb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ec(a.segments,c,0,b),g.ec(a.segments,c+1,0,b)))},m1=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.V=c;this.P=d;this.D=e;this.U=f;this.environmentData=this.player.S();this.C=new l1;this.I=-1;this.B=this.u=this.j=null;this.J=new g.K(this.NO,1E3,this);this.events=new g.cz(this);g.J(this,this.J);g.J(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.xC);this.xC();this.NO()},hXa=function(a){return a.j&&a.j.C?a.j.C+a.player.pd()<a.player.getCurrentTime():!1},iXa=function(a,b){var c=g.ay(g.yy(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.hq(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.wua(e);if(h){e=g.yy(a.u,a.policy,{});a.u.Jk(e,h);iXa(a,a.u);break a}f?a.player.qa("capfail",{status:e.status}):(a.player.Qi().po("fcb_r"),h=a.u.j[0].Ha,null!=a.P&&a.I!==h&&(f=a.u.j[0],a.D?a.P(e.response,1E3*(f.startTime+a.player.pd())):a.P(e.responseText,1E3*(f.startTime+a.player.pd())),a.I=h))}a.u=null;a.B=null}}).Ii(function(e){a.u=
null;
a.B=null;var f;a.player.qa("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;gXa(a.C,a.u.j[0].Ha)},n1=function(a,b){g.QI.call(this,b.S());
this.j=a;this.G=b;this.B=null;this.D=!1;this.I=g.qB(this.G.S())&&!this.j.isManifestless},kXa=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.SI(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.vVa.get(e);null==n&&(n=jXa[e]||jXa[e.replace(/-/g,"_")],g.vVa.set(e,n));h=n||h}c.push(new g.KC({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},lXa=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},mXa=function(a,b,c){var d=
[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.SI(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},o1=function(a){if(!nXa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(oXa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},p1=function(a,b,c,d,e,f,h,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Kd);a.params.Kd&&Object.assign(n,a.params.Kd);Object.assign(n,c.Kd);m.Kd=n;g.W.call(this,{F:"div",L:"caption-window",T:{id:"caption-window-"+a.id,dir:1===m.Lg?"rtl":"ltr",tabindex:"0",lang:m.lang},R:[{F:"span",L:"captions-text",T:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.ma=!1;this.u=a;this.Ca=this.xa=null;this.playerWidth=f;this.playerHeight=h;this.I=null;this.maxWidth=.96*f;this.maxHeight=
.96*h;this.j=m;this.Gb=c;this.Ga=b;this.C=this.va("captions-text");this.ib=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.V=e/360*16;!l.bb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.V=f/640*16);this.type=0;this.Qa=this.V*pXa(n);a=new g.fu(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.wU,this);a.subscribe("dragmove",this.vU,this);a.subscribe("dragend",this.uU,this);this.Ya=this.Ra=
0;b="";this.j.windowOpacity&&(a=o1(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":qXa[this.j.textAlign]};this.ib&&(a["border-radius"]=b?this.Qa/8+"px":"");if(this.B=2===this.u.params.Lg||3===this.u.params.Lg)b=this.element,c="vertical-rl",1===this.j.FJ&&(c="vertical-lr"),g.vc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Qk(b,"-o-writing-mode",c),g.Qk(b,"-webkit-writing-mode",c),g.Qk(b,"writing-mode",
c),g.Qk(b,"text-orientation","upright"),g.N(b,"ytp-vertical-caption"),3===this.u.params.Lg&&(g.Qk(b,"text-orientation",""),g.Qk(b,"transform","rotate(180deg)"));g.Qk(this.element,a);switch(this.j.zj){case 0:case 1:case 2:g.N(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.N(this.element,"ytp-caption-window-bottom")}},pXa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},rXa=function(a,b){var c={},d=b.background?b.background:a.j.Kd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Kd.backgroundOpacity;d=o1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ib&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Qa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.V*pXa(b)+"px";d=1;e=b.color||a.j.Kd.color;if(b.color||null!=b.textOpacity)e=o1(e),d=null==b.textOpacity?a.j.Kd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.yF&&(h=e=b.yF);var l=a.V/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.rq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Kd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.dX&&(c.visibility="hidden");1===b.gO&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.uB||g.xr,3===a.u.params.Lg?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Zk||2===b.Zk||3===b.Zk||4===b.Zk||5===b.Zk)if(g.uB)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Zk){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},sXa=function(a){a.I=g.rg("SPAN");
g.Qk(a.I,{display:"block"});g.N(a.I,"caption-visual-line");a.C.appendChild(a.I)},tXa=function(a,b){var c=g.rg("SPAN");
g.Qk(c,{display:"inline-block","white-space":"pre-wrap"});g.Qk(c,rXa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.Qk(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Qk(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},uXa=function(a,b,c){a.ma=a.ma||!!c;
var d={};Object.assign(d,a.j.Kd);Object.assign(d,c||b.j);Object.assign(d,a.Gb.Kd);(c=!a.I)&&sXa(a);for(var e=a.xa&&a.Ca&&g.Me(d,a.Ca)?a.xa:tXa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(sXa(a),e=tXa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.sg(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.uB||!g.Sk(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Sk(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.ve?g.Qk(e,m,"1em"):g.Qk(e,m,"0.5em")))}a.Ca=d;a.xa=e;a.D.push(b)},q1=function(a,b,c,d){g.QI.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ma=d;this.C=b.XE},r1=function(a,b,c,d,e,f,h,l){p1.call(this,a,b,c,d,e,f,h,l);
this.type=1},s1=function(a,b,c,d,e,f,h,l){p1.call(this,a,b,c,d,e,f,h,l);
this.type=2;this.J=[];this.U=this.P=this.Ja=0;this.Z=NaN;this.Za=0;this.sb=null;this.Pa=new g.K(this.b_,433,this);g.N(this.element,"ytp-caption-window-rollup");g.J(this,this.Pa);g.Qk(this.element,"overflow","hidden")},vXa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.FJ&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},wXa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.rowCount,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.P=d;b=Math;c=b.max;isNaN(a.Z)&&((d=a.j.Qo)?(e=g.rg("SPAN"),g.yg(e,"\u2013".repeat(d)),g.Qk(e,rXa(a,a.j.Kd)),a.C.appendChild(e),a.Z=e.offsetWidth,a.C.removeChild(e)):a.Z=0);d=a.C;a.U=c.call(b,a.Z,a.Za,(a.B?d.offsetHeight:d.offsetWidth)+1)},xXa=function(a,b){wXa(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.P-c;if(c!==a.Ja){var d=0<c&&0===a.Ja;b||isNaN(c)||d||(g.N(a.element,"ytp-rollup-mode"),g.xn(a.Pa));g.Qk(a.C,"transform",vXa(a,c));a.Ja=c}wXa(a)},t1=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.tv.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},u1=function(a,b,c,d,e){g.tv.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},yXa=function(a){var b="_"+v1++;
return new u1(0,0x8000000000000,0,b,a)},AXa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Qe){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=zXa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new t1(a,b,e,c,l,d,m)}switch(m.Qe){case 9:case 10:m.Zk=1;break;case 11:m.Zk=2;break;case 12:m.Zk=3;break;case 13:m.Zk=4;break;case 14:m.Zk=5}return new t1(a,b,e,c,l.textContent||"",d,m)},zXa=function(a,b,c,d,e){var f=g.rq(),h=
f?g.rg("DIV"):g.rg("RUBY"),l=g.rg("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.rg("DIV"):g.rg("RP");a.textContent=b;h.appendChild(a);b=f?g.rg("DIV"):g.rg("RT");b.textContent=c;h.appendChild(b);c=e.Qe;if(10===c||11===c||12===c||13===c||14===c)if(g.Qk(b,"text-emphasis-style","filled circle"),g.Qk(b,"text-emphasis-color","currentcolor"),g.Qk(b,"webkit-text-emphasis","filled circle"),11===e.Qe||13===e.Qe)g.Qk(b,"webkit-text-emphasis-position","under left"),g.Qk(b,"text-emphasis-position","under left");c=!0;if(4===e.Qe||7===e.Qe||12===e.Qe||
14===e.Qe)g.Qk(h,"ruby-position","over"),g.Qk(h,"-webkit-ruby-position","before");else if(5===e.Qe||6===e.Qe||11===e.Qe||13===e.Qe)g.Qk(h,"ruby-position","under"),g.Qk(h,"-webkit-ruby-position","after"),c=!1;e=f?g.rg("DIV"):g.rg("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Qk(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Qk(f,"display","none"),f=f.nextElementSibling,g.Qk(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Qk(h.lastElementChild,"display","none"),d?(g.Qk(h,"padding-top","0.6em"),g.Qk(f,"top","0")):(g.Qk(h,"padding-bottom","0.6em"),g.Qk(f,"bottom","0")));return h},w1=function(){g.I.apply(this,arguments)},x1=function(a){w1.call(this);
this.C=a;this.pens={};this.P={};this.U={};this.D="_"+v1++;this.J={};this.B=this.j=null;this.I=!0},y1=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},z1=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},A1=function(a,b){a=y1(a,b);
return void 0!==a?a:null},C1=function(a,b){a=a.getAttribute(b);
if(null!=a)return B1.test(a),a},BXa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.U[d]:a.C);a=A1(b,"mh");null!=a&&(c.ev=a);a=A1(b,"ju");null!=a&&(c.textAlign=a);a=A1(b,"pd");null!=a&&(c.Lg=a);a=A1(b,"sd");null!=a&&(c.FJ=a);a=C1(b,"wfc");null!=a&&(c.windowColor=a);b=y1(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},CXa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.P[d]);a=A1(b,"ap");null!=a&&(c.zj=a);a=y1(b,"cc");null!=a&&(c.Qo=a);a=y1(b,"ah");null!=a&&(c.zi=a);a=y1(b,"rc");null!=a&&(c.rowCount=a);b=y1(b,"av");null!=b&&(c.al=b);return c},DXa=function(a,b,c,d){var e={};
Object.assign(e,CXa(a,b));Object.assign(e,BXa(a,b));d?g.Me(e,a.C)?(d=a.D,e=a.C):d="_"+v1++:d=b.getAttribute("id")||"_"+v1++;a=y1(b,"t")+c;b=y1(b,"d")||0x8000000000000;if(2===e.Lg||3===e.Lg)c=e.rowCount,e.rowCount=e.Qo,e.Qo=c;return new u1(a,b,0,d,e)},D1=function(a){w1.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},E1=function(a){a=g.Of(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},EXa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.rowCount=a);b=b.ccColCount;void 0!==b&&(f.Qo=b);if(2===f.Lg||3===f.Lg)b=f.rowCount,f.rowCount=f.Qo,f.Qo=b;return new u1(c,d,0,e,f)},G1=function(){this.B=this.time=this.mode=this.u=0;
this.C=new F1(this);this.D=new F1(this);this.j=[];this.clear()},GXa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Sq:a,
No:b,result:0};a=FXa[a];b=FXa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.No===d;if(d)return{Sq:a,No:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Sq:a,No:b,result:2};return{Sq:a,No:b,result:3}},IXa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,HXa(a.C,b,c,d))},JXa=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.r(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?IXa(a,d.HM,d.IM,b):1===d.type&&a.u&496&&HXa(a.D,d.HM,d.IM,b);a.j.length=0},H1=function(){this.type=0},I1=function(){this.state=this.No=this.Sq=0},KXa=function(){this.timestamp=this.j=0},J1=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new H1;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new KXa}},K1=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},PXa=function(a,b){switch(a){case 0:return LXa[(b&127)-32];
case 1:return MXa[b&15];case 2:return NXa[b&31];case 3:return OXa[b&31]}return 0},L1=function(a){return a.B[a.row][a.u]},M1=function(a,b,c){2<=b&&1<a.u&&(--a.u,L1(a).j=0);
var d=L1(a);d.timestamp=a.D.time+0;d.j=PXa(b,c);32>a.u&&a.u++},QXa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},N1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},O1=function(a){a.row=0<a.j?a.j:1;
a.u=1;N1(a,0,15)},P1=function(a){this.B=a;
this.D=0;this.style=new H1;this.I=new J1(this.B);this.J=new J1(this.B);this.text=new J1(this.B);this.u=this.I;this.C=this.J;this.j=this.u},Q1=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(K1(d,c),O1(a.u),O1(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(K1(d,c),N1(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},RXa=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},SXa=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},F1=function(a){this.j=a;
this.D=0;this.B=new P1(this.j);this.I=new P1(this.j);this.u=new I1;this.C=this.B},HXa=function(a,b,c,d){a.u.update();
b=GXa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Sq;c=b.No;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&M1(a,0,b),c&96&&M1(a,0,c),0!==b&&0!==c&&3===a.style.type&&K1(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Sq=e,b.No=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;QXa(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));N1(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:M1(b.j,0,32);break a;case 48:57===c?(d=b.j,L1(d).j=0,32>d.u&&d.u++):M1(b.j,1,c&15)}break;case 2:c&32&&M1(b.j,2,c&31);break;case 3:c&32&&M1(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:RXa(b);
break;case 33:d=b.j;1<d.u&&(--d.u,L1(d).j=0);break;case 36:d=b.j;b=L1(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Q1(b,2,d);break;case 38:Q1(b,3,d);break;case 39:Q1(b,4,d);break;case 40:M1(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);O1(d);SXa(b);break;case 43:SXa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:K1(a,d)}N1(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;K1(a,d);QXa(a,b,b+1,a.j-1);N1(a,a.row,1)}break;case 46:N1(b.C,0,15);break;case 47:K1(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,RXa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},TXa=function(){},R1=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},S1=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},T1=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},U1=function(a,b){w1.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new G1;this.j.u=1<<this.track},V1=function(a){if("string"===typeof a)return!1;
a=new R1(a,8,0);return UXa(a)},UXa=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==T1(a))return!1;
a.version=S1(a);if(1<a.version)return!1;S1(a);S1(a);S1(a);return!0},W1=function(){w1.call(this)},VXa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new t1(b,c,d,e.id,p.nodeValue,f||0<n,g.Je(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);VXa(a,b,c,d,e,!0,p,q,m)}}},X1=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},WXa=function(a,b,c,d){d=Object.assign({ev:0},d);
return new u1(a,b,c,"_"+v1++,d)},Y1=function(a,b){g.I.call(this);
this.G=a;this.environmentData=b;this.j=null;this.u=this.G.Fu()},bYa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.u&&b){var f=e,h=XXa(a,b,d),l=[];try{for(var m=g.r(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.wJ;l="string"!==typeof q?l.concat(YXa(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(ZXa(a,q,t)):l.concat($Xa(a,c,q,t))}var u=l}catch(x){g.S(x),a.clear(),u=[]}if(0!==u.length)return u}b=aYa(b);if(!b)return[];try{return"string"!==typeof b?YXa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?ZXa(a,b,d):$Xa(a,c,b,d)}catch(x){return g.S(x),a.clear(),[]}},aYa=function(a){if("string"===
typeof a||V1(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.Cx(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.ox(a)},XXa=function(a,b,c){if("string"===typeof b||V1(b))return[{trackData:b,
wJ:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.jta(d);if(a.u&&e){var f=g.bta(e),h=g.cta(e);e=e.j;f&&e&&a.u.Mz(e,f,h)}f=g.Lx(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.r(f.entries());for(h=f.next();!h.done;h=f.next())e=g.r(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.ox(e),a.push({trackData:e,wJ:c+1E3*h});cYa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
cYa=function(a,b,c){var d=g.Cx(a,0,1836476516),e=9E4;
d&&(e=g.Dx(d)||9E4);d=0;var f=g.Lx(a,1836019558);f=g.r(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.r(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.Cx(a,l.dataOffset,1953653094))&&(l=g.Cx(a,l.dataOffset,1952867444))&&(l=g.Jx(l)/e*1E3,0===h&&(d=l),b[h].wJ=l-d+c||c*h*1E3)}},YXa=function(a,b,c,d,e){if(!V1(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new U1(e,b));return a.j.u(c,d)},ZXa=function(a,b,c){a.j||(a.j=new W1);
a=a.j.u(b,c);.01>Math.random()&&g.uu(Error("Deprecated subtitles format in web player: WebVTT"));return a},$Xa=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new D1(dYa(b))),a.j.u(c,d)}catch(f){return g.S(f),[]}var e=g.BZ(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new x1(dYa(b),a.environmentData)),a.j.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},dYa=function(a){var b=
{};
if(a=g.NC(a))b.lang=a,g.NTa.test(a)&&(b.Lg=1);return b},a2=function(a){g.NI.call(this,a);
var b=this;this.G=a;this.environmentData=this.G.S();this.videoData=this.G.getVideoData();this.Za=this.G.Wa();this.C={Kd:{}};this.D={Kd:{}};this.Z=[];this.P={};this.Ga={};this.V=!1;this.Kb=g.MD(this.videoData);this.Ra=g.xDa(this.videoData,this.G);this.Gb=!!this.videoData.captionTracks.length;this.Yb=!!this.videoData.Gc;this.Ja="3"===this.environmentData.controlsType;this.u=this.I=this.J=this.Ca=this.Ya=null;this.Pa=new Y1(this.G,this.environmentData);this.j=null;this.ea=new g.cz(this);this.Qa=new g.W({F:"div",
L:"ytp-caption-window-container",T:{id:"ytp-caption-window-container"}});var c=null,d=g.Co("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.qo(d));this.storage=c;var e;this.ib=!(null==(e=a.Ed())||!e.Fz());this.B=eYa(this);this.U=!this.B&&this.Ja&&this.ib&&this.Ra;g.J(this,this.Pa);this.B?this.xa=this.ma=null:(this.ma=new g.vn(this.XJ,void 0,this),g.J(this,this.ma),this.xa=new g.K(this.w0,2E3,this),g.J(this,this.xa));g.J(this,this.ea);this.environmentData.K("caption_window_container_killswitch")||
g.xI(this.player,this.Qa.element,4);g.J(this,this.Qa);this.B||this.ea.N(a,"resize",this.ZJ);(this.sb=!g.Vt()&&!this.G.isFullscreen()&&!this.B&&!this.U&&!this.environmentData.K("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.ea.N(a,"resize",this.lZ);this.ea.N(a,"onPlaybackAudioChange",this.yY);this.ea.N(a,g.vv("captions"),function(f){b.onCueRangeEnter(f)});
this.ea.N(a,g.wv("captions"),function(f){b.onCueRangeExit(f)});
Z1(this,$1(this)||{});this.player.Ia("captionssupportchanged")},hYa=function(a){if(1===a.environmentData.Ya||1===a.videoData.Kw||"alwayson"===g.wD(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.environmentData.Ya){var c;g.sB(a.environmentData)?c=fYa(a):c=gYa(a,"module-enabled");if(null!=c)return!!c}c=j1(a.player.getAudioTrack(),k1(a.environmentData));var d=g.wD(a.videoData,"yt:cc");if(void 0===b2(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.wD(a.videoData,"yt:cc")},c2=function(a,
b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},b2=function(a){var b=void 0,c=g.Rq(g.Qq.getInstance(),65);
if(g.sB(a.environmentData)&&null!=c){if(null!=fYa(a))return!1;b=!c}return b},iYa=function(a){var b;
a.Kb?b=new q1(a.environmentData,a.videoData,a.player.getAudioTrack(),a.player):a.Ra?b=new n1(a.videoData.j,a.player):a.Gb?b=new g.RI(a.environmentData,a.videoData,a.player.getAudioTrack()):b=new g.TI(a.environmentData,a.videoData.Gc,a.videoData.videoId,g.kya(a.videoData),a.videoData.rl);return b},e2=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.Yb?!1:a.Gb?!1:!0);b=g.OI(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.environmentData.captionsLanguagePreference,g.wD(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.NC(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||d2(a)}return null},d2=function(a){return a.I&&a.I.j},f2=function(a){var b=d2(a);
return!!b&&a.j===b},jYa=function(a){var b=j1(a.player.getAudioTrack(),k1(a.environmentData)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=e2(a,a.V):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&c2(a)?c=d2(a):b2(a)||a.V||hYa(a)?c=e2(a,a.V):c2(a)&&(c=d2(a));if(a.B||a.U){var d=g.OI(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.rg("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.LC(f));h.setAttribute("srclang",g.NC(f));h.setAttribute("id",f.toString());a.U||h.setAttribute("src",a.u.zr(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.G.Ed();c.Zw(b);c=c.df();
a.ib&&a.ea.N(c.textTracks,"change",a.I_)}else!a.j&&c&&g2(a,c),a.player.Ia("onCaptionsTrackListChanged"),a.player.Ia("onApiChange")},kYa=function(a,b){var c=a.G.Ed().df().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},g2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.V=c,a.V&&(g.sB(a.environmentData)?h2(a,!!b):i2(a,"module-enabled",!!b)));a.j=b;c2(a)&&(a.j=d2(a));a.load()},mYa=function(a,b){if(b instanceof u1){var c=a.P[b.id];
c&&c.u!==b&&(c.dispose(),delete a.P[b.id],c=null);c||(c=lYa(a,b))&&(a.P[b.id]=c)}else c=b.windowId,a.Ga[c]||(a.Ga[c]=[]),a.Ga[c].push(b)},nYa=function(a,b){a.environmentData.K("caption_window_container_killswitch")?g.xI(a.player,b,4):a.Qa.element.appendChild(b)},lYa=function(a,b){var c=a.Za.getVideoContentRect(!0).height,d=a.Za.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.NC(a.j):null;e&&g.NTa.test(e)&&(b.params.Lg=1);e=a.Za.getPlayerSize();switch(null!=b.params.ev?b.params.ev:1<b.j.length?1:0){case 1:return new r1(b,a.C,a.D,d,c,e.width,e.height,a.environmentData.experiments);case 2:return new s1(b,a.C,a.D,d,c,e.width,e.height,a.environmentData.experiments);default:return new p1(b,a.C,a.D,d,c,e.width,e.height,a.environmentData.experiments)}},Z1=function(a,b,c){c=void 0===c?!1:c;
var d=j2.Kd;a.C={};Object.assign(a.C,j2);a.C.Kd={};Object.assign(a.C.Kd,d);a.D={Kd:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;B1.test(f);e.Kd.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;B1.test(f);e.Kd.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||j2.windowColor;B1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Kd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Kd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Kd;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Kd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=j2.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Kd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Kd.fontFamily=f;a.loaded&&a.ZJ();c&&(a.environmentData.K("web_player_local_storage_for_captions_setting_killswitch")?i2(a,"display-settings",b):g.Su("yt-player-caption-display-settings",b,2592E3))},k2=function(a,b,c){b&&!a.J?(b=yXa({Lg:0,
lang:"es-419"}),a.J=[b,new t1(b.start,b.end-b.start,0,b.id,null!=c?c:"Los subt\u00edtulos tendr\u00e1n este aspecto:")],a.player.Sd(a.J)):!b&&a.J&&(oYa(a,a.J),a.J=null)},oYa=function(a,b){a.player.Jg(b);
b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.Yb(a.Z,c.value);g.wn(a.ma)},gYa=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},i2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},h2=function(a,b){a.G.isInline()||g.Su("yt-player-sticky-caption",b,2592E3)},fYa=function(a){if(!a.G.isInline())return g.Tu("yt-player-sticky-caption")},$1=function(a){return a.environmentData.K("web_player_local_storage_for_captions_setting_killswitch")?gYa(a,"display-settings"):g.Tu("yt-player-caption-display-settings")},eYa=function(a){var b,c=!(null==(b=a.G.Ed())||
!b.Ez());
return a.Ja&&c&&!a.Ra};
g.GN.prototype.Ix=g.ea(33,function(a){var b=2;this.xa.has(a)?b=0:g.NGa(this,a)&&(b=1);return b});
g.tQ.prototype.Ix=g.ea(32,function(a){return this.Zc.Ix(a)});
g.GN.prototype.Mz=g.ea(31,function(a,b,c){this.ma.set(a,{WA:b,Xw:c})});
g.tQ.prototype.Mz=g.ea(30,function(a,b,c){this.Zc.Mz(a,b,c)});
g.gJ.prototype.Xt=g.ea(29,function(){for(var a=g.kg(document,"track",void 0,this.j),b=0;b<a.length;b++)g.vg(a[b])});
g.qN.prototype.Xt=g.ea(28,function(){this.mediaElement.Xt()});
g.gJ.prototype.Fz=g.ea(27,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.qN.prototype.Fz=g.ea(26,function(){return this.mediaElement.Fz()});
g.gJ.prototype.Ez=g.ea(25,function(){return!!this.j.textTracks});
g.qN.prototype.Ez=g.ea(24,function(){return this.mediaElement.Ez()});
g.gJ.prototype.Zw=g.ea(23,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.qN.prototype.Zw=g.ea(22,function(a){this.mediaElement.Zw(a)});
g.QI.prototype.DI=g.ea(21,function(){return!1});
g.QI.prototype.Ip=g.ea(20,function(){});
g.RI.prototype.Ip=g.ea(19,function(a,b,c){var d=this;this.isDisposed();b=this.zr(a,b);this.uo();this.j=g.eq(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.TI.prototype.Ip=g.ea(18,function(a,b,c){var d=this;this.isDisposed();b=this.zr(a,b);this.uo();this.j=g.eq(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.iQ.prototype.Vx=g.ea(8,function(){return this.J});
g.LS.prototype.Vx=g.ea(7,function(){var a;return(null==(a=g.zI(this))?void 0:a.Fu())||null});
g.qI.prototype.Fu=g.ea(6,function(){return this.app.Vx()});
g.lS.prototype.Fu=g.ea(5,function(){var a;return(null==(a=this.Ea)?void 0:a.Vx())||null});
var jXa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",
as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",
bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",
chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",
dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",
ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",
grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",
io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",
km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",
lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",
mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",
nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",
pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",
sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",
smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",
tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",
uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",
zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};l1.prototype.contains=function(a){a=g.hc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
l1.prototype.length=function(){return this.segments.length/2};
g.w(m1,g.I);g.k=m1.prototype;g.k.Y=function(){g.I.prototype.Y.call(this);this.B&&this.B.cancel()};
g.k.xC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.pd();var b=this.j;this.j=g.Qb(this.V.yn(a).j);b!==this.j&&this.U&&this.U()};
g.k.reset=function(){this.C=new l1;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.NO=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Fo(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.Cw(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai){var c=this.player.Fu();if(c){var d=a.j[0].Ha;if(b=c.Dk(a.j[0].B,d,a.j[0].j.info.id,3))if(c=c.Ix(d),0===c)b&&(a.B=new g.Tw(b));else if(2===c){this.J.start();hXa(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.j[0].duration?(this.C.contains(a.j[0].Ha)||
iXa(this,a),this.j=g.Qb(a.j)):!this.environmentData.K("force_caption_seek_for_live_killswitch")&&hXa(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.w(n1,g.QI);g.k=n1.prototype;g.k.Ip=function(a,b,c){var d=this;this.uo();b=lXa(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?mXa(this,b,"386"):mXa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.vDa(this.environmentData);this.B=new m1(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.My(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.DI=function(){var a=this.D;this.D=!1;return a};
g.k.Wu=function(a){var b=this.I?[new g.KC({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.KC({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?kXa(this,"386"):kXa(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.PI(this.u,c.value);a()};
g.k.uo=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.zr=function(){return""};
var B1=/^#(?:[0-9a-f]{3}){1,2}$/i,oXa=/#(.)(.)(.)/,nXa=/^#(?:[0-9a-f]{3}){1,2}$/i;var qXa=["left","right","center","justify"];g.w(p1,g.W);g.k=p1.prototype;g.k.wU=function(a,b){var c=g.Zk(this.element,this.element.parentElement);this.Ra=a-c.x;this.Ya=b-c.y;g.N(this.element,"ytp-dragging")};
g.k.vU=function(a,b){var c=g.al(this.element);a=a-this.Ra-.02*this.playerWidth;var d=b-this.Ya-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Of(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.Of(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Of(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.Of(c,0,1);this.u.params.zj=b;this.u.params.al=c;this.u.params.zi=a;this.j.zj=b;this.j.al=c;this.j.zi=a;this.Ga.zj=b;this.Ga.al=c;this.Ga.zi=a;this.QQ()};
g.k.uU=function(){g.Fn(this.element,"ytp-dragging")};
g.k.QQ=function(){this.Nv(this.D)};
g.k.getType=function(){return this.type};
g.k.Nv=function(a){var b=Math.min(this.EN(),this.maxWidth),c=this.DN(),d="";3===this.u.params.Lg&&(d="rotate(180deg)");g.Qk(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.kF(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.zi+2;d=this.j.zj;switch(d){case 0:case 3:case 6:(b=this.j.Kd.fontSizeIncrement)&&0<b&&2!==this.j.Lg&&3!==
this.j.Lg&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.al+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Qk(this.element,
a)};
g.k.kF=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.ma||this.D.length>b)b=0,this.ma=!1,this.D=[],this.I=this.Ca=this.xa=null,g.tg(this.C);for(;b<a.length;b++)uXa(this,a[b])};
g.k.EN=function(){return 0};
g.k.DN=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.w(q1,g.QI);q1.prototype.Ip=function(a,b,c){fXa(this.videoData.videoId,a.vssId,c)};
q1.prototype.Wu=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.PI(this.u,c.value);a()};g.w(r1,p1);r1.prototype.kF=function(a){var b=this.u.j;p1.prototype.kF.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,pYa);var e=c.j;var f=d}uXa(this,c,d)}};
var pYa={dX:!0};g.w(s1,p1);g.k=s1.prototype;g.k.QQ=function(){g.yn(this.Pa)};
g.k.b_=function(){g.Fn(this.element,"ytp-rollup-mode");this.Nv(this.sb,!0)};
g.k.DN=function(){return this.B?this.U:this.P};
g.k.EN=function(){return this.B?this.P:this.U};
g.k.Nv=function(a,b){this.sb=a;if(this.u.params.rowCount){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.Za=this.U;this.P=this.U=0;p1.prototype.Nv.call(this,a);xXa(this,b)}p1.prototype.Nv.call(this,a)};g.w(t1,g.tv);t1.prototype.toString=function(){return g.tv.prototype.toString.call(this)};g.w(u1,g.tv);u1.prototype.toString=function(){return g.tv.prototype.toString.call(this)};
var v1=0;g.w(w1,g.I);w1.prototype.u=function(){return[]};
w1.prototype.reset=function(){};g.w(x1,w1);x1.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
x1.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=z1(a,"b");
null!=l&&(h.bold=l);l=z1(a,"i");null!=l&&(h.italic=l);l=z1(a,"u");null!=l&&(h.underline=l);l=A1(a,"et");null!=l&&(h.charEdgeStyle=l);l=A1(a,"of");null!=l&&(h.offset=l);l=C1(a,"bc");null!=l&&(h.background=l);l=C1(a,"ec");null!=l&&(h.yF=l);l=C1(a,"fc");null!=l&&(h.color=l);l=A1(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=y1(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=y1(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=y1(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=A1(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Qe=10<l?l-1:l);a=A1(a,"hg");null!=a&&(h.gO=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.U[c]=BXa(this,a);break;case "wp":c=a.getAttribute("id"),this.P[c]=CXa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=DXa(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!z1(a,"a");l=(y1(a,"t")||0)+l;var m=y1(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var u=q[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.pens[u]:null)&&u.Qe&&(1===u.Qe?(u=q.slice(t,t+
4),4===u.length&&(x=AXa(l,m,f,h,n,u,this.pens),t+=3)):x=AXa(l,m,f,h,n,[y],this.pens)),!x){var z=y;x=l;y=m;u=f;var D=h,H=n,G=z.textContent?z.textContent:"",L=z.getAttribute("p");L=L?this.pens[L]:null;z=y1(z,"t")||0;x=new t1(x+z,y-z,H,u,G,D,L)}}else x=new t1(l,m,n,f,u.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=DXa(this,a,b,!0),d.push(this.j)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var qYa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(D1,w1);D1.prototype.reset=function(){this.B.clear()};
D1.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.yF=E1(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=E1(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=E1(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Qe=10<h?h-1:h,f.Zk=qYa.get(f.Qe));e.hgHorizGroup&&(f.gO=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.ev=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Lg=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.FJ=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=E1(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.zi=e.ahHorPos),void 0!==e.apPoint&&(f.zj=e.apPoint),void 0!==e.avVerPos&&(f.al=e.avVerPos),void 0!==e.ccCols&&(f.Qo=e.ccCols),void 0!==e.rcRows&&(f.rowCount=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=EXa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+v1++,h=EXa(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);
var m=!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.j.get(t.pPenId));if(2===(null!=h.params.ev?h.params.ev:1<h.j.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Qe)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.j.get(z))&&z.Qe&&2===z.Qe?(z=p[t+2].pPenId,z=this.j.get(z),!z||!z.Qe||3>z.Qe?t=!1:(z=p[t+3].pPenId,t=(z=this.j.get(z))&&
z.Qe&&2===z.Qe?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var D=this.j.get(p[l+2].pPenId);u=zXa(u,x,z,t,D);m=new t1(d,e,n,f,u,m,y);l+=3}else m=new t1(d+x,e-x,n,h.id,u,m,y||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};G1.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
G1.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var FXa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];H1.prototype.set=function(a){this.type=a};
H1.prototype.get=function(){return this.type};
I1.prototype.clear=function(){this.state=0};
I1.prototype.update=function(){this.state=2===this.state?1:0};
I1.prototype.isValid=function(){return 0!==this.state};
I1.prototype.matches=function(a,b){return this.isValid()&&a===this.Sq&&b===this.No};
KXa.prototype.reset=function(){this.timestamp=this.j=0};
J1.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
J1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
J1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var LXa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],MXa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],NXa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],OXa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];P1.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
F1.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};TXa.prototype.C=function(){};g.w(R1,TXa);R1.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+v1++;c=c/1E3-this.I;d=d/1E3-this.I;a=new u1(c,d-c,5,f,{textAlign:0,zj:0,zi:2.5*b,al:5.33*a});e=new t1(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(U1,w1);U1.prototype.u=function(a){a=new R1(a,a.byteLength,this.B);if(UXa(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=T1(a)*(1E3/45):1===a.version&&(a.B=4294967296*T1(a)+T1(a)),a.D=S1(a);0<a.D;a.D--){var b=S1(a),c=S1(a),d=S1(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,HM:c,IM:d,order:b.j.length}))}JXa(this.j,a);return a.u}return[]};
U1.prototype.reset=function(){this.j.clear()};g.w(W1,w1);
W1.prototype.u=function(a,b){var c=[];a=a.split(rYa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!sYa.test(e)){var h=l2.exec(e);if(h&&4<=h.length){var l=X1(h[1]),m=X1(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,u="";n=g.r(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.al=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.zi=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.zi=0;break;case 1:h.zi=100;break;case 2:h.zi=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.zj=q}e=e.substring(l2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=WXa(l,m,5,u),m=new t1(l,m,5,f.id,h,!1,g.Je(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(tYa),1===q.length?(h=5,u=WXa(l,m,h,u)):(p=h=6,u=Object.assign({Qo:32},u),u=new u1(l,m,p,"_"+v1++,u)),c.push(u),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(x=g.BZ("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,VXa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=X1(n)+f}l2.lastIndex=0}}return c};
var sYa=/^NOTE/,rYa=/(?:\r\n|\r|\n){2,}/,l2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),tYa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.sN.NB(W1,{u:"wvppt"});g.w(Y1,g.I);Y1.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
Y1.prototype.reset=function(){this.j&&this.j.reset()};
Y1.prototype.Y=function(){g.I.prototype.Y.call(this);this.clear()};var j2={windowColor:"#080808",windowOpacity:0,textAlign:2,zj:7,zi:50,al:100,Kd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(a2,g.NI);g.k=a2.prototype;g.k.Y=function(){if(this.B||this.U){var a=this.G.Ed();a&&!a.isDisposed()&&a.Xt()}else k2(this,!1);g.NI.prototype.Y.call(this);this.player.Ia("captionssupportchanged")};
g.k.Is=function(){if(this.Ja)return this.B||this.U;var a=j1(this.player.getAudioTrack(),k1(this.environmentData));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?c2(this):b2(this)||c2(this)?!0:hYa(this)};
g.k.load=function(){var a=this;g.NI.prototype.load.call(this);var b=!this.environmentData.K("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.Pa.clear(),this.B?kYa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Ip(this.j,"json3",function(c,d,e,f){c&&(a.u.DI()&&(a.Z=[],a.G.zf("captions"),g.wn(a.ma),a.Pa.reset()),c=bYa(a.Pa,c,d,e,f),a.player.Sd(c,void 0,a.Ra),!a.V||a.U||f2(a)||g.fB(a.environmentData)||g.YA(a.environmentData)||(g.zn(a.xa),
c=yXa({zj:0,zi:5,al:5,rowCount:2,textAlign:0,Lg:0,lang:"es-419"}),a.Ca=[c],d=["Haz clic en "," para acceder a la configuraci\u00f3n."],a.Ya||(e=new g.iG(g.zG()),g.J(a,e),a.Ya=e.element),e=c.end-c.start,(f=g.LC(a.j))&&a.Ca.push(new t1(c.start,e,0,c.id,f)),a.Ca.push(new t1(c.start,e,0,c.id,d[0]),new t1(c.start,e,0,c.id,a.Ya,!0),new t1(c.start,e,0,c.id,d[1],!0)),a.player.Sd(a.Ca),g.xn(a.xa)),!a.V||a.U||f2(a)||(g.sB(a.environmentData)?h2(a,!0):i2(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.Ts()),
a.V=!1)}),!b||this.B||this.U||f2(this)||this.player.Ia("captionschanged",g.MC(this.j))),b||(this.j&&!f2(this)?this.player.Ia("captionschanged",g.MC(this.j)):this.player.Ia("onCaptionsTrackListChanged"))):(this.u=iYa(this),g.J(this,this.u),this.u.Wu(function(){jYa(a)}))};
g.k.unload=function(){this.B&&this.j?kYa(this,!1):(this.xa&&g.zn(this.xa),this.player.zf("captions"),this.Z=[],this.u&&this.u.uo(),this.Pa.clear(),this.J&&this.player.Sd(this.J),this.ZJ());g.NI.prototype.unload.call(this);this.player.Ts();this.player.Ia("captionschanged",{})};
g.k.create=function(){this.Is()&&this.load()};
g.k.I_=function(){for(var a=this.G.Ed().df().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.OI(this.u.u,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.j:null)!==b&&g2(this,b,!0)};
g.k.D1=function(){!this.j&&this.B||this.unload()};
g.k.onCueRangeEnter=function(a){this.Z.push(a);g.wn(this.ma)};
g.k.onCueRangeExit=function(a){g.Yb(this.Z,a);this.u instanceof n1&&this.u.I&&this.player.Jg([a]);g.wn(this.ma)};
g.k.getCaptionWindowContainerId=function(){return this.Qa.element.id};
g.k.w0=function(){oYa(this,this.Ca);this.Ca=null};
g.k.XJ=function(){var a=this;if(!this.sb||!this.B){this.ma.stop();g.ica(this.Ga);this.Z.sort(g.uv);var b=this.Z;if(this.J){var c=g.Ll(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.r(b);for(c=b.next();!c.done;c=b.next())mYa(this,c.value);b={};c=g.r(Object.entries(this.P));for(var d=c.next();!d.done;b={qq:b.qq,lk:b.lk},d=c.next()){var e=g.r(d.value);d=e.next().value;e=e.next().value;b.qq=d;b.lk=e;this.Ga[b.qq]?(b.lk.element.parentNode||(b.lk instanceof s1||b.lk instanceof r1||g.Ce(this.P,function(f){return function(h,l){l!==f.qq&&h.u.params.zj===f.lk.u.params.zj&&h.u.params.zi===f.lk.u.params.zi&&h.u.params.al===f.lk.u.params.al&&(h.dispose(),delete a.P[l]);
return l===f.qq}}(b),this),nYa(this,b.lk.element)),b.lk.Nv(this.Ga[b.qq])):(b.lk.dispose(),delete this.P[b.qq])}}};
g.k.A0=function(){Z1(this,{},!0);this.environmentData.K("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Ia("captionssettingschanged")};
g.k.xW=function(){var a=j2.Kd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:j2.windowColor,windowOpacity:j2.windowOpacity};var b=$1(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.UR=function(a,b){var c={};Object.assign(c,$1(this));Object.assign(c,a);Z1(this,c,b);this.player.Ia("captionssettingschanged")};
g.k.ZJ=function(){!this.B&&this.loaded&&(g.ze(this.P,function(a,b){a.dispose();delete this.P[b]},this),this.XJ())};
g.k.Wf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Of(b,-2,4);this.UR({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&g2(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.environmentData.B&&(g.sB(this.environmentData)?h2(this,!!b):i2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Pa(b))break;if(g.Je(b)){g2(this,null,!0);break}a=g.OI(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||
c&&e.languageName!==b.languageName||(c=b.translationLanguage?eXa(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.fva(),a=g.NC(c),b.length&&a===b[b.length-1]||(b.push(a),g.Su("yt-player-caption-language-preferences",b)),g2(this,c,!0))}else return this.loaded&&this.j&&!f2(this)?g.MC(this.j):{};return"";case "tracklist":return this.u?g.ak(g.OI(this.u.u,!(!b||!b.includeAsr)),function(f){return g.MC(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||k2(this,!!b);break;case "sampleSubtitlesCustomized":this.B||k2(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.environmentData.B&&a.push("stickyLoading");return a};
g.k.EG=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.environmentData.K("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.NC(a));return{cc:b}}return{}};
g.k.n1=function(){this.loaded&&this.j&&!f2(this)?(g.sB(this.environmentData)?h2(this,!1):i2(this,"module-enabled",!1),this.unload(),c2(this,!0)&&g2(this,d2(this),!1)):this.AR()};
g.k.AR=function(){this.loaded&&this.j&&!f2(this)||g2(this,f2(this)||!this.j?e2(this,!0):this.j,!0)};
g.k.yY=function(){var a=f2(this);c2(this,a)?g2(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Is()&&(a?g2(this,e2(this),!1):this.load()))};
g.k.lZ=function(){var a=this.G.Ed();a&&!a.isDisposed()&&a.Xt();this.G.isFullscreen()?(this.B=this.Ja=!0,this.loaded&&jYa(this)):(this.Ja="3"===this.environmentData.controlsType,this.B=eYa(this));g2(this,this.j)};
g.sN.NB(a2,{XJ:"smucd"});g.MI("captions",a2);})(_yt_player);
