(function(g){var window=this;'use strict';var BYa=function(a,b){a.Ia("onAutonavCoundownStarted",b)},C2=function(a,b,c){g.O(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.uf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.BC&&(b.lengthText?(e=b.lengthText||null,f=b.Qr||null):b.lengthSeconds&&(e=g.kH(b.lengthSeconds),f=g.kH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.xC(d).type;var l=b instanceof g.BC?b.isLivePlayback:null,m=b instanceof g.BC?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,t=[],u=[];n&&t.push(n);p&&(t.push(p),u.push(p));q&&u.push(q);c={title:b.title,author:n,author_and_views:t.join(" \u2022 "),aria_label:b.ariaLabel||
g.WE("Ver $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.gm(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:u.join(" \u2022 "),autoplayAlternativeHeader:b.Mo};b instanceof g.AC&&(c.playlist_length=b.playlistLength);a.update(c)},D2=function(a){var b=a.S(),c=b.j;
g.W.call(this,{F:"a",L:"ytp-autonav-suggestion-card",T:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},R:[{F:"div",Aa:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],T:{style:"{{background}}"},R:[{F:"div",T:{"aria-label":"{{timestamp}}"},Aa:["ytp-autonav-timestamp"],X:"{{duration}}"},{F:"div",Aa:["ytp-autonav-live-stamp"],X:"En vivo"},{F:"div",
Aa:["ytp-autonav-upcoming-stamp"],X:"Pr\u00f3ximamente"},{F:"div",L:"ytp-autonav-list-overlay",R:[{F:"div",L:"ytp-autonav-mix-text",X:"Mix"},{F:"div",L:"ytp-autonav-mix-icon"}]}]},{F:"div",Aa:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],X:"{{title}}"},{F:"div",Aa:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],X:"{{author}}"},{F:"div",Aa:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],X:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.j=c;this.Ka("click",this.onClick);this.Ka("keypress",this.onKeyPress)},F2=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{F:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.D=b;this.cancelCommand=void 0;this.u=0;b=a.S();var d=b.j;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.N(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.K("web_rounded_thumbnails")&&e.push("rounded-thumbnail");this.j=new g.W({F:"div",L:"ytp-autonav-endscreen-upnext-container",T:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}",
"data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},R:[{F:"div",L:"ytp-autonav-endscreen-upnext-header"},{F:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",X:"{{autoplayAlternativeHeader}}"},{F:"a",L:"ytp-autonav-endscreen-link-container",T:{href:"{{url}}",target:d?b.J:""},R:[{F:"div",Aa:e,T:{style:"{{background}}"},R:[{F:"div",T:{"aria-label":"{{timestamp}}"},Aa:["ytp-autonav-timestamp"],X:"{{duration}}"},{F:"div",Aa:["ytp-autonav-live-stamp"],
X:"En vivo"},{F:"div",Aa:["ytp-autonav-upcoming-stamp"],X:"Pr\u00f3ximamente"}]},{F:"div",L:"ytp-autonav-endscreen-video-info",R:[{F:"div",L:"ytp-autonav-endscreen-premium-badge"},{F:"div",L:"ytp-autonav-endscreen-upnext-title",X:"{{title}}"},{F:"div",L:"ytp-autonav-endscreen-upnext-author",X:"{{author}}"},{F:"div",L:"ytp-autonav-view-and-date",X:"{{views_and_publish_time}}"},{F:"div",L:"ytp-autonav-author-and-view",X:"{{author_and_views}}"}]}]}]});g.J(this,this.j);this.j.ra(this.element);d||this.N(this.j.va("ytp-autonav-endscreen-link-container"),
"click",this.BL);this.G.zb(this.element,this,115127);this.G.zb(this.j.va("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({F:"div",L:"ytp-autonav-overlay"});g.J(this,this.overlay);this.overlay.ra(this.element);this.B=new g.W({F:"div",L:"ytp-autonav-endscreen-button-container"});g.J(this,this.B);this.B.ra(this.element);this.cancelButton=new g.W({F:"button",Aa:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":
""],T:{"aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},X:"Cancelar"});g.J(this,this.cancelButton);this.cancelButton.ra(this.B.element);this.cancelButton.Ka("click",this.BU,this);this.G.zb(this.cancelButton.element,this,115129);this.playButton=new g.W({F:"a",Aa:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],T:{href:"{{url}}",role:"button","aria-label":"Reproducir siguiente video"},
X:"Reproducir ahora"});g.J(this,this.playButton);this.playButton.ra(this.B.element);this.playButton.Ka("click",this.BL,this);this.G.zb(this.playButton.element,this,115130);this.C=new g.K(function(){E2(c)},500);
g.J(this,this.C);this.AL();this.N(a,"autonavvisibility",this.AL)},I2=function(a){var b=a.G.Ej(!0,a.G.isFullscreen());
g.O(a.element,"ytp-autonav-endscreen-small-mode",a.eg(b));g.O(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.mD);g.O(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.Ne());g.O(a.G.getRootNode(),"countdown-running",a.Xi());g.O(a.element,"ytp-player-content",a.G.Ne());g.Qk(a.overlay.element,{width:b.width+"px"});if(!a.Xi()){a.G.Ne()?G2(a,Math.round(H2(a)/1E3)):G2(a);b=!!a.suggestion&&!!a.suggestion.Mo;var c=a.G.Ne()||!b;g.O(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.O(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.lG(a.B,a.G.Ne())}},E2=function(a){var b=H2(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);G2(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Xi()?a.select(!0):a.Xi()&&a.C.start()},H2=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.VE;return-1===a||void 0===a?8E3:a}return 0<=a.G.fp()?a.G.fp():g.Xz(a.G.S().experiments,"autoplay_time")||1E4},G2=function(a,b){b=void 0===b?-1:b;
a=a.j.va("ytp-autonav-endscreen-upnext-header");g.tg(a);if(0<=b){b=String(b);var c="A continuaci\u00f3n, en $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="A continuaci\u00f3n, en $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.sg("A continuaci\u00f3n, en $SECONDS".slice(0,d)));var e=g.rg("span");g.Cn(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.yg(e,b);a.appendChild(e);a.appendChild(g.sg("A continuaci\u00f3n, en $SECONDS".slice(d+c.length)));return}}g.yg(a,"Siguiente")},J2=function(a,
b){g.W.call(this,{F:"div",
Aa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},K2=function(a){g.W.call(this,{F:"div",
Aa:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},R:[{F:"div",L:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{F:"span",L:"ytp-upnext-top",R:[{F:"span",L:"ytp-upnext-header",X:"A continuaci\u00f3n"},{F:"span",L:"ytp-upnext-title",X:"{{title}}"},{F:"span",L:"ytp-upnext-author",X:"{{author}}"}]},{F:"a",L:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente video"},R:[{F:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},R:[{F:"circle",L:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",L:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",L:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",L:"ytp-upnext-bottom",R:[{F:"span",L:"ytp-upnext-cancel"},{F:"span",L:"ytp-upnext-paused",
X:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.api=a;this.cancelButton=null;this.D=this.va("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.K(this.OA,5E3,this);this.u=0;var b=this.va("ytp-upnext-cancel");this.cancelButton=new g.W({F:"button",Aa:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},X:"Cancelar"});g.J(this,this.cancelButton);this.cancelButton.Ka("click",this.CU,
this);this.cancelButton.ra(b);this.cancelButton&&this.api.zb(this.cancelButton.element,this,115129);g.J(this,this.C);this.api.zb(this.element,this,18788);b=this.va("ytp-upnext-autoplay-icon");this.N(b,"click",this.DU);this.api.zb(b,this,115130);this.CL();this.N(a,"autonavvisibility",this.CL);this.N(a,"mdxnowautoplaying",this.nZ);this.N(a,"mdxautoplaycanceled",this.oZ);g.O(this.element,"ytp-upnext-mobile",this.api.S().isMobile)},CYa=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.VE;return-1===a||void 0===a?8E3:a}return 0<=a.api.fp()?a.api.fp():g.Xz(a.api.S().experiments,"autoplay_time")||1E4},L2=function(a,b){b=CYa(a,b);
var c=Math,d=c.min;var e=(0,g.R)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Xi()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Xi()&&a.j.start()},M2=function(a){J2.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({F:"div",L:"ytp-suggestion-panel",R:[{F:"div",Aa:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],X:"M\u00e1s videos"}]});this.J=new g.W({F:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new F2(this.player);g.J(this,this.u);this.u.ra(this.element);a.getVideoData().wd?this.j=this.u:(this.j=new K2(a),g.xI(this.player,this.j.element,4),g.J(this,this.j));this.overlay=new g.W({F:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.ra(this.element);this.C=new g.cz(this);g.J(this,this.C);g.J(this,this.table);this.table.ra(this.element);this.table.show();g.J(this,this.J);this.J.ra(this.table.element);this.hide()},N2=function(a){var b=a.Ne();
b!==a.D&&(a.D=b,a.player.W("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},O2=function(a){J2.call(this,a,"subscribecard-endscreen");
this.j=new g.W({F:"div",L:"ytp-subscribe-card",R:[{F:"img",L:"ytp-author-image",T:{src:"{{profilePicture}}"}},{F:"div",L:"ytp-subscribe-card-right",R:[{F:"div",L:"ytp-author-name",X:"{{author}}"},{F:"div",L:"html5-subscribe-button-container"}]}]});g.J(this,this.j);this.j.ra(this.element);var b=a.getVideoData();this.subscribeButton=new g.SJ("Suscribirse",null,"Anular suscripci\u00f3n",null,!0,!1,b.hk,b.subscribed,"trailer-endscreen",null,null,a);g.J(this,this.subscribeButton);this.subscribeButton.ra(this.j.va("html5-subscribe-button-container"));
this.N(a,"videodatachange",this.Da);this.Da();this.hide()},P2=function(a){var b=a.S(),c=g.gz||g.OA?{style:"will-change: opacity"}:void 0,d=b.j,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.W.call(this,{F:"a",Aa:e,T:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},R:[{F:"div",L:"ytp-videowall-still-image",T:{style:"{{background}}"}},{F:"span",L:"ytp-videowall-still-info",R:[{F:"span",L:"ytp-videowall-still-info-bg",R:[{F:"span",L:"ytp-videowall-still-info-content",T:c,R:[{F:"span",L:"ytp-videowall-still-info-title",X:"{{title}}"},{F:"span",
L:"ytp-videowall-still-info-author",X:"{{author_and_views}}"},{F:"span",L:"ytp-videowall-still-info-live",X:"En vivo"},{F:"span",L:"ytp-videowall-still-info-duration",X:"{{duration}}"}]}]}]},{F:"span",Aa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],R:[{F:"span",L:"ytp-videowall-still-listlabel-icon"},"Lista de reproducci\u00f3n",{F:"span",L:"ytp-videowall-still-listlabel-length",R:[" (",{F:"span",X:"{{playlist_length}}"},")"]}]},{F:"span",Aa:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],R:[{F:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{F:"span",L:"ytp-videowall-still-listlabel-length",X:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.cz(this);g.J(this,this.j);this.Ka("click",this.onClick);this.Ka("keypress",this.onKeyPress);this.j.N(a,"videodatachange",this.onVideoDataChange);a.Vh(this.element,this);this.onVideoDataChange()},Q2=function(a){J2.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.P=null;this.u=new g.cz(this);g.J(this,this.u);this.U=a.K("web_rounded_thumbnails");this.I=new g.K(function(){g.N(b.element,"ytp-show-tiles")},0);
g.J(this,this.I);var c=new g.W({F:"button",Aa:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Anterior"},R:[g.qG()]});g.J(this,c);c.ra(this.element);c.Ka("click",this.HU,this);this.table=new g.iG({F:"div",L:"ytp-endscreen-content"});g.J(this,this.table);this.table.ra(this.element);c=new g.W({F:"button",Aa:["ytp-button","ytp-endscreen-next"],T:{"aria-label":"Siguiente"},R:[g.rG()]});g.J(this,c);c.ra(this.element);c.Ka("click",this.GU,this);a.getVideoData().wd?this.j=new F2(a,!0):this.j=new K2(a);
g.J(this,this.j);g.xI(this.player,this.j.element,4);this.hide()},R2=function(a){return g.yI(a.player)&&a.bx()&&!a.C},S2=function(a){var b=a.Ne();
b!==a.J&&(a.J=b,a.player.W("autonavvisibility"))},T2=function(a){g.NI.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.cz(this);g.J(this,this.listeners);this.env=a.S();DYa(a)?(this.B=!0,EYa(this),this.j?this.endScreen=new M2(a):this.endScreen=new Q2(this.player)):this.env.Se?this.endScreen=new O2(this.player):this.endScreen=new J2(this.player);g.J(this,this.endScreen);g.xI(this.player,this.endScreen.element,4);FYa(this);this.listeners.N(a,"videodatachange",this.onVideoDataChange,this);this.listeners.N(a,g.vv("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.N(a,g.wv("endscreen"),function(c){b.onCueRangeExit(c)})},EYa=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.ri&&a.u===b.wd)return!1;a.j=b.ri;a.u=b.wd;return!0},DYa=function(a){a=a.S();
return!a.C&&a.Gc&&!a.Se},FYa=function(a){a.player.zf("endscreen");
var b=a.player.getVideoData();b=new g.tv(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.tv(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Sd([b,c])};
g.qI.prototype.fp=g.ea(4,function(){return this.app.fp()});
g.LS.prototype.fp=g.ea(3,function(){return this.getVideoData().iQ});g.w(D2,g.W);D2.prototype.select=function(){(this.G.ll(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ax||void 0)||this.G.K("web_player_endscreen_double_log_fix_killswitch"))&&this.G.qb(this.element)};
D2.prototype.onClick=function(a){g.lJ(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
D2.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.gt(a)||(this.select(),g.ft(a))}};g.w(F2,g.W);g.k=F2.prototype;g.k.tA=function(a){this.suggestion!==a&&(this.suggestion=a,C2(this.j,a),this.playButton.updateValue("url",this.suggestion.gm()),I2(this))};
g.k.Xi=function(){return 0<this.u};
g.k.Pv=function(){this.Xi()||(this.u=Date.now(),E2(this),BYa(this.G,H2(this)),g.O(this.G.getRootNode(),"countdown-running",this.Xi()))};
g.k.qs=function(){this.oo();E2(this);var a=this.j.va("ytp-autonav-endscreen-upnext-header");a&&g.yg(a,"Siguiente")};
g.k.oo=function(){this.Xi()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.oo()};
g.k.BL=function(a){g.lJ(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.qb(this.playButton.element):a.currentTarget===this.j.va("ytp-autonav-endscreen-link-container")&&(a=this.j.va("ytp-autonav-endscreen-link-container"),this.G.Ua(a,!0),this.G.qb(a)),this.select())};
g.k.BU=function(){this.G.qb(this.cancelButton.element);g.sI(this.G,!0);this.cancelCommand&&this.G.Ia("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){var c;this.cancelCommand=null==(c=b.mS)?void 0:c.command};
g.k.AL=function(){var a=this.G.Ne();this.D&&this.kb!==a&&g.lG(this,a);I2(this);this.G.Ua(this.element,a);this.G.Ua(this.cancelButton.element,a);this.G.Ua(this.j.va("ytp-autonav-endscreen-link-container"),a);this.G.Ua(this.playButton.element,a)};
g.k.eg=function(a){return 400>a.width||459>a.height};g.w(J2,g.W);g.k=J2.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.bx=function(){return!1};
g.k.Ne=function(){return!1};
g.k.yO=function(){return!1};g.w(K2,g.W);g.k=K2.prototype;g.k.OA=function(){this.notification&&(this.C.stop(),this.pc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.tA=function(a){this.suggestion=a;C2(this,a,"hqdefault.jpg")};
g.k.CL=function(){g.lG(this,this.api.Ne());this.api.Ua(this.element,this.api.Ne());this.api.Ua(this.va("ytp-upnext-autoplay-icon"),this.api.Ne());this.cancelButton&&this.api.Ua(this.cancelButton.element,this.api.Ne())};
g.k.wZ=function(){window.focus();this.OA()};
g.k.Pv=function(a){var b=this;this.Xi()||(g.wt("a11y-announce","A continuaci\u00f3n "+this.suggestion.title),this.u=(0,g.R)(),this.j=new g.K(function(){L2(b,a)},25),L2(this,a),BYa(this.api,CYa(this,a)));
g.Fn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.Xi=function(){return!!this.j};
g.k.qs=function(){this.oo();this.u=(0,g.R)();L2(this);g.N(this.element,"ytp-upnext-autoplay-paused")};
g.k.oo=function(){this.Xi()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.S().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.OA(),this.notification=new Notification("A continuaci\u00f3n",{body:this.suggestion.title,icon:this.suggestion.uf()}),this.B=this.N(this.notification,"click",this.wZ),this.C.start())}this.oo();this.api.nextVideo(!1,a)};
g.k.DU=function(a){!g.xg(this.cancelButton.element,g.bt(a))&&g.lJ(a,this.api)&&(this.api.Ne()&&this.api.qb(this.va("ytp-upnext-autoplay-icon")),this.select())};
g.k.CU=function(){this.api.Ne()&&this.cancelButton&&this.api.qb(this.cancelButton.element);g.sI(this.api,!0)};
g.k.nZ=function(a){this.api.getPresentingPlayerType();this.show();this.Pv(a)};
g.k.oZ=function(){this.api.getPresentingPlayerType();this.oo();this.hide()};
g.k.Y=function(){this.oo();this.OA();g.W.prototype.Y.call(this)};g.w(M2,J2);g.k=M2.prototype;g.k.create=function(){J2.prototype.create.call(this);this.C.N(this.player,"appresize",this.Jw);this.C.N(this.player,"onVideoAreaChange",this.Jw);this.C.N(this.player,"videodatachange",this.onVideoDataChange);this.C.N(this.player,"autonavchange",this.DL);this.C.N(this.player,"autonavcancel",this.EU);this.onVideoDataChange()};
g.k.show=function(){J2.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.sI(this.player,!1);g.yI(this.player)&&this.bx()&&!this.B?(N2(this),2===this.videoData.autonavState?this.player.S().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Pv():3===this.videoData.autonavState&&this.j.qs()):(g.sI(this.player,!0),N2(this));this.Jw()};
g.k.hide=function(){J2.prototype.hide.call(this);this.j.qs();N2(this)};
g.k.Jw=function(){var a=this.player.Ej(!0,this.player.isFullscreen());N2(this);I2(this.u);g.O(this.element,"ytp-autonav-cancelled-small-mode",this.eg(a));g.O(this.element,"ytp-autonav-cancelled-tiny-mode",this.UB(a));g.O(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Qk(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.O(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.QD(this.videoData);b&&(this.j.tA(b),this.j!==this.u&&this.u.tA(b));for(b=0;b<GYa.length;++b){var c=GYa[b];if(a&&a[c]){this.videos[b]=new D2(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,C2(d,c));g.J(this,this.videos[b]);this.videos[b].ra(this.J.element)}}}this.Jw()}};
g.k.DL=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.oo(),this.kb&&this.Jw()):(this.I=!0,this.Ne()&&(2===a?this.j.Pv():3===a&&this.j.qs()))};
g.k.EU=function(a){a?this.DL(1):(this.B=null,this.I=!1)};
g.k.bx=function(){return 1!==this.videoData.autonavState};
g.k.eg=function(a){return(910>a.width||459>a.height)&&!this.UB(a)&&!(400>=a.width||360>=a.height)};
g.k.UB=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Ne=function(){return this.kb&&g.yI(this.player)&&this.bx()&&!this.B};
var GYa=[1,3,2,4];g.w(O2,J2);O2.prototype.Da=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.hk;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(P2,g.W);P2.prototype.select=function(){(this.api.ll(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ax||void 0)||this.api.K("web_player_endscreen_double_log_fix_killswitch"))&&this.api.qb(this.element)};
P2.prototype.onClick=function(a){g.lJ(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
P2.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.gt(a)||(this.select(),g.ft(a))}};
P2.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.S();this.u=a.D?!1:b.j};g.w(Q2,J2);g.k=Q2.prototype;g.k.create=function(){J2.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Rm();this.u.N(this.player,"appresize",this.Rm);this.u.N(this.player,"onVideoAreaChange",this.Rm);this.u.N(this.player,"videodatachange",this.onVideoDataChange);this.u.N(this.player,"autonavchange",this.FE);this.u.N(this.player,"autonavcancel",this.FU);a=this.videoData.autonavState;a!==this.P&&this.FE(a);this.u.N(this.element,"transitionend",this.J_)};
g.k.destroy=function(){g.au(this.u);g.oe(this.stills);this.stills=[];J2.prototype.destroy.call(this);g.Fn(this.element,"ytp-show-tiles");this.I.stop();this.P=this.videoData.autonavState};
g.k.bx=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){J2.prototype.show.call(this);g.Fn(this.element,"ytp-show-tiles");this.player.S().isMobile?g.yn(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.sI(this.player,!1);R2(this)?(S2(this),2===this.videoData.autonavState?this.player.S().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Pv():3===this.videoData.autonavState&&this.j.qs()):(g.sI(this.player,!0),S2(this))};
g.k.hide=function(){J2.prototype.hide.call(this);this.j.qs();S2(this)};
g.k.J_=function(a){g.bt(a)===this.element&&this.Rm()};
g.k.Rm=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.N(this.element,"ytp-endscreen-paginate");var a=this.G.Ej(!0,this.G.isFullscreen()),b=g.nI(this.G);b&&(b=b.Gf()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,u=e<=h-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=q*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.$k(a,m,n);g.Qk(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.j.tA(g.QD(this.videoData));this.j instanceof F2&&I2(this.j);g.O(this.element,"ytp-endscreen-takeover",R2(this));S2(this);m+=4;n+=4;for(f=c=0;f<
b;f++)for(h=0;h<e;h++)if(p=c,t=0,d&&f>=b-2&&h>=e-2?t=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(t=2):t=2),p=g.Pf(p+this.B,l),0!==t){q=this.stills[c];q||(q=new P2(this.player),this.stills[c]=q,a.appendChild(q.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+t)/e)-u-4,z=Math.floor(m*(f+t)/b)-x-4;g.Wk(q.element,x,u);g.$k(q.element,z,y);g.Qk(q.element,"transitionDelay",(h+f)/20+"s");g.O(q.element,"ytp-videowall-still-mini",1===t);g.O(q.element,"ytp-videowall-still-large",2<t);
this.U&&(t=Math.max(z,y),g.O(q.element,"ytp-videowall-still-round-large",256<=t),g.O(q.element,"ytp-videowall-still-round-medium",96<t&&256>t),g.O(q.element,"ytp-videowall-still-round-small",96>=t));p=this.videoData.suggestions[p];q.suggestion!==p&&(q.suggestion=p,t=q.api.S(),u=g.Dn(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",C2(q,p,u),g.QA(t)&&(u=p.gm(),x={},t.Z&&g.cI(x,t.loaderUrl),u=g.Dh(u,g.bI(x,"emb_rel_end")),q.updateValue("url",u)),(p=(p=p.sessionData)&&p.itct)&&
q.api.Xk(q.element,p));c++}g.O(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.vg(e.element),g.ne(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Rm())};
g.k.GU=function(){this.B+=this.stills.length;this.Rm()};
g.k.HU=function(){this.B-=this.stills.length;this.Rm()};
g.k.yO=function(){return this.j.Xi()};
g.k.FE=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.oo(),this.kb&&this.Rm()):(this.D=!0,this.kb&&R2(this)&&(2===a?this.j.Pv():3===a&&this.j.qs()))};
g.k.FU=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Ua(this.stills[a].element,!0);this.FE(1)}else this.C=null,this.D=!1;this.Rm()};
g.k.Ne=function(){return this.kb&&R2(this)};g.w(T2,g.NI);g.k=T2.prototype;g.k.Is=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!DYa(this.player)||b;var c=a.Cf||a.u.isMusic(),d=this.player.Gx();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Ne=function(){return this.endScreen.Ne()};
g.k.mX=function(){return this.Ne()?this.endScreen.yO():!1};
g.k.Y=function(){this.player.zf("endscreen");g.NI.prototype.Y.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.mP;if(b&&b.videoId){var c=this.player.fb().Pd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.RL?a=!1:(this.player.ll(b.videoId,void 0,void 0,!0,!0,b),c&&c.cC("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.NI.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.NI.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Is()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){FYa(this);this.B&&EYa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new M2(this.player):this.endScreen=new Q2(this.player),g.J(this,this.endScreen),g.xI(this.player,this.endScreen.element,4))};g.MI("endscreen",T2);})(_yt_player);
